spring:
  application:
    structurizr:
      apikey: 6e6063ea-9234-4b4b-8052-dfc0b9e0285e
      apisecret: xxx
    name: micro-documentation
  profiles:
    active: dev
  jackson:
    serialization:
      indent_output: true
  datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:testdb:MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
  h2:
    console:
      enabled: true
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
          hibernate:
              dialect: org.hibernate.dialect.H2Dialect

server:
    port: 9080

#management:
#    contextPath: /management
#    add-application-context-header: false
#
#info:
#    name: ${spring.application.name}
#    description:  micro-documentation
#    environment: ${spring.profiles.active}
#    version: 1.0
